gs=git status $*
ga=git add .
gc=git commit -m "$*"
gp=git push
gcom=git add . $T git commit -m "$*" $T git push
newgit=git add . $T git commit --allow-empty-message -m "" $T git push
gitprep=git stash $T git pull $T git stash pop
gitIgnoreRm=git rm -r --cached . $T git add . $T git commit -m "Update .gitignore"
ls=dir /b $*
ll=dir /a /q $*
la=dir /a $*
mkcd=mkdir "$1" $T cd "$1"
ps=tasklist $*
kill=taskkill /f /im $*
grep=findstr $*
vim=notepad $*
nf=type nul ^> "$1"
edit=notepad $*
envvar=rundll32.exe sysdm.cpl,EditEnvironmentVariables
wifi=netsh wlan show interfaces
ipconfig=ipconfig /all $*
ports=netstat -ano $*
which=where $*
cat=type $*
synctime=gsudo w32tm /resync
inst=scoop install $*
remove=scoop uninstall $*
wg=winget install $* --accept-package-agreements --disable-interactivity
up=gsudo topgrade $T scoop cleanup * $T scoop cache rm *
cleanup=scoop cleanup * $T scoop cache rm *
screensaver=control desk.cpl,,@screensaver
edit-profile=notepad "C:\Users\Dan\aliases.cmd"
clear=cls
pwd=echo %CD%
history=doskey /history
..=cd ..
...=cd ..\..