#!/bin/zsh

/usr/libexec/polkit-mate-authentication-agent-1 &
deskflow &
$HOME/AppImages/beeper.appimage --no-sandbox %U &
flameshot &
qlipper &
cortile &
kdeconnect-indicator &
/usr/lib/notification-daemon/notification-daemon
