#!/bin/zsh

/usr/libexec/polkit-mate-authentication-agent-1 &
numlockx &
nm-applet &
blueman-applet &
deskflow &
$HOME/AppImages/beeper.appimage --no-sandbox %U &
flameshot &
qlipper &
cortile &
kdeconnect-indicator &
/usr/lib/notification-daemon/notification-daemon &
setxkbmap -option compose:ralt &
kdeconnectd &
