#!/bin/zsh

#/usr/lib/x86_64-linux-gnu/libexec/polkit-kde-authentication-agent-1 &
#flatpak run org.deskflow.deskflow/x86_64/master &
$HOME/AppImages/beeper.appimage --no-sandbox %U &
#ksnip &
flameshot &
qlipper &
#rustdesk &
#killall kwalletd6 &
cortile &
kdeconnect-indicator &
#/home/dkendall/AppImages/fantascenedynamicwallpaper.appimage %F --platform xcb
/usr/lib/notification-daemon/notification-daemon
#sleep 10 && wmctrl -s 1
