speed=4.0
af=scaletempo=stride=30:overlap=.2:search=10
hwdec=auto-safe
alang=eng,en,enm
slang=en,eng
sub-auto=fuzzy
profile=gpu-hq
scale=ewa_lanczossharp
deband=yes
video-sync=display-resample
interpolation=yes
tscale=oversample
keep-open=yes
geometry=50%:50%
